# vim:fileencoding=utf-8:foldmethod=marker

#: Reset {{{

unbind C-b
unbind C-f
unbind %
unbind "'"
unbind -T copy-mode-vi h
unbind -T copy-mode-vi j
unbind -T copy-mode-vi k
unbind -T copy-mode-vi l

#: }}}

#: Global configs {{{

set -g default-shell @zsh@
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm*:Tc"

set -g mouse on
unbind -n MouseDrag1Pane
unbind -Tcopy-mode MouseDrag1Pane

set -sg escape-time 1
set -s extended-keys on
set -g history-limit 50000
set -g bell-action none
set -g focus-events on

#: }}}

#: Global key bindings {{{

set -g prefix C-Space
bind C-Space send-prefix
bind \; command-prompt

set -g mode-keys vi
set -g status-keys vi
set -g repeat-time 1000

bind p paste-buffer
bind C-p choose-buffer

#: }}}

#: Pane {{{

bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

bind -r K resize-pane -U 5
bind -r J resize-pane -D 5
bind -r H resize-pane -L 5
bind -r L resize-pane -R 5

bind -r C-h swap-pane -d -t -1
bind -r C-l swap-pane -d -t +1

bind -r x kill-pane

#: }}}

#: Window {{{

setw -g monitor-activity on
set -g visual-activity on

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

bind n new-window -c "#{pane_current_path}"
bind r command-prompt "rename-window %%"
bind C-x kill-window

bind -r [ previous-window
bind -r ] next-window
bind -r C-[ swap-window -d -t -1
bind -r C-] swap-window -d -t +1

bind -r - split-window -h -c "#{pane_current_path}"
bind -r = split-window -v -c "#{pane_current_path}"

#: }}}

#: Session {{{

bind R command-prompt "rename-session %%"
bind q confirm-before -p "kill-session #S? (y/n)" kill-session

#: }}}

#: Vim mode {{{

bind Escape copy-mode

bind -T copy-mode-vi k send -X cursor-up
bind -T copy-mode-vi K send -N 5 -X cursor-up
bind -T copy-mode-vi j send -X cursor-down
bind -T copy-mode-vi J send -N 5 -X cursor-down
bind -T copy-mode-vi h send -X cursor-left
bind -T copy-mode-vi H send -X start-of-line
bind -T copy-mode-vi l send -X cursor-right
bind -T copy-mode-vi L send -X end-of-line

bind -T copy-mode-vi v send -X begin-selection
#bind -T copy-mode-vi y send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

#: }}}

#: Status {{{

%if #{TMUX}
set status-bg red
%endif

set -g status-interval 5

#: }}}
