{ config, lib, pkgs, ... }:

let
  cfg = config.martin.terminal.ghostty;

  hasPackage = name: builtins.hasAttr name pkgs;

  bool = b: if b then "true" else "false";

  # `toString` renders floats with six decimals (1.100000); trim the trailing
  # zeros so the generated config looks like a hand-written one.
  trimZeros = s:
    if lib.hasSuffix "0" s && lib.stringLength s > 1 then
      trimZeros (lib.substring 0 (lib.stringLength s - 1) s)
    else
      s;

  formatFloat = f:
    let
      s = toString f;
      trimmed = if lib.hasInfix "." s then trimZeros s else s;
    in
    if lib.hasSuffix "." trimmed then trimmed + "0" else trimmed;

  themeLines =
    (
      if cfg.theme.auto then
        [ "theme = light:${cfg.theme.light},dark:${cfg.theme.dark}" ]
      else
        [ "theme = ${cfg.theme.fixed}" ]
    )
    ++ lib.optional (cfg.theme.boldIsBright != null)
      "bold-is-bright = ${bool cfg.theme.boldIsBright}";

  transparencyLines =
    lib.optional (cfg.transparency.opacity != null)
      "background-opacity = ${formatFloat cfg.transparency.opacity}"
    ++ lib.optional (cfg.transparency.blur != null)
      "background-blur = ${toString cfg.transparency.blur}";

  fontStyleLine = suffix: value:
    lib.optional (value != null) "font-style${suffix} = ${value}";

  fontLines = [
    ''font-family = "${cfg.font.family}"''
    "font-size = ${toString cfg.font.size}"
  ]
  ++ lib.optional cfg.font.thicken "font-thicken = true"
  ++ lib.optional (cfg.font.adjustCellHeight != null)
    "adjust-cell-height = ${cfg.font.adjustCellHeight}"
  ++ fontStyleLine "" cfg.font.style.regular
  ++ fontStyleLine "-italic" cfg.font.style.italic
  ++ fontStyleLine "-bold" cfg.font.style.bold
  ++ fontStyleLine "-bold-italic" cfg.font.style.boldItalic;

  windowLines = [
    "macos-titlebar-style = ${cfg.window.titlebarStyle}"
    "macos-option-as-alt = ${bool cfg.window.optionAsAlt}"
    "window-save-state = ${cfg.window.saveState}"
    "window-padding-x = ${toString cfg.window.padding.x}"
    "window-padding-y = ${toString cfg.window.padding.y}"
    "window-padding-balance = ${bool cfg.window.padding.balance}"
    "window-padding-color = ${cfg.window.padding.color}"
    "quit-after-last-window-closed = ${bool cfg.window.quitAfterLastClosed}"
    "confirm-close-surface = ${bool cfg.window.confirmClose}"
  ]
  ++ lib.optional (cfg.window.colorspace != null)
    "window-colorspace = ${cfg.window.colorspace}"
  ++ lib.optional (cfg.window.minimumContrast != null)
    "minimum-contrast = ${formatFloat cfg.window.minimumContrast}"
  ++ lib.optional (cfg.window.title != null)
    "title = ${cfg.window.title}";

  cursorLines = [
    "cursor-style = ${cfg.cursor.style}"
    "cursor-style-blink = ${bool cfg.cursor.blink}"
    "mouse-hide-while-typing = ${bool cfg.cursor.hideMouseWhileTyping}"
  ];

  clipboardLines = lib.optionals cfg.clipboard.enable [
    "clipboard-read = allow"
    "clipboard-write = allow"
    "copy-on-select = clipboard"
  ];

  scrollbackLines = [
    "scrollback-limit = ${toString cfg.scrollback.lines}"
  ];

  shellLines = [
    "shell-integration = ${cfg.shellIntegration.shell}"
    "shell-integration-features = ${lib.concatStringsSep "," cfg.shellIntegration.features}"
  ];

  quickTermLines = lib.optionals cfg.quickTerminal.enable [
    "quick-terminal-position = ${cfg.quickTerminal.position}"
    "quick-terminal-animation-duration = ${formatFloat cfg.quickTerminal.animationDuration}"
  ];

  splitKeybinds = lib.optionals cfg.splits.enable [
    "# Splits — create"
    "keybind = cmd+d=new_split:right"
    "keybind = cmd+shift+d=new_split:down"
    "keybind = cmd+shift+f=toggle_split_zoom"
    "keybind = cmd+shift+enter=toggle_fullscreen"
    ""
    "# Splits — navigate (cmd+opt+arrow avoids Neovim conflicts)"
    "keybind = cmd+alt+left=goto_split:left"
    "keybind = cmd+alt+right=goto_split:right"
    "keybind = cmd+alt+up=goto_split:top"
    "keybind = cmd+alt+down=goto_split:bottom"
    ""
    "# Splits — resize"
    "keybind = cmd+ctrl+left=resize_split:left,20"
    "keybind = cmd+ctrl+right=resize_split:right,20"
    "keybind = cmd+ctrl+up=resize_split:up,20"
    "keybind = cmd+ctrl+down=resize_split:down,20"
    ""
    "# Splits — equalize"
    "keybind = cmd+shift+0=equalize_splits"
  ];

  tabKeybinds = lib.optionals cfg.tabs.enable [
    "# Tabs"
    "keybind = cmd+shift+left=previous_tab"
    "keybind = cmd+shift+right=next_tab"
  ];

  section = title: lines:
    if lines == [ ] then [ ] else [ "# ── ${title} ──" ] ++ lines ++ [ "" ];

  configText = lib.concatStringsSep "\n" (
    [
      "# Ghostty config — generated by Home Manager (modules/home/ghostty.nix)"
      "# Edit modules/home/ghostty.nix and host enablement, not this file."
      ""
    ]
    ++ section "Theme" themeLines
    ++ section "Transparency" transparencyLines
    ++ section "Font" fontLines
    ++ section "Window" windowLines
    ++ section "Cursor" cursorLines
    ++ section "Clipboard" clipboardLines
    ++ section "Scrollback" scrollbackLines
    ++ section "Shell integration" shellLines
    ++ section "Quick terminal" quickTermLines
    ++ section "Keybinds" (splitKeybinds ++ lib.optional (splitKeybinds != [ ] && tabKeybinds != [ ]) "" ++ tabKeybinds)
  );
in
{
  options.martin.terminal.ghostty = {
    enable = lib.mkEnableOption "Ghostty terminal config under Home Manager (replaces unmanaged ~/.config/ghostty/config)" // {
      default = true;
    };

    theme = {
      auto = lib.mkEnableOption "Auto-match macOS appearance using separate light and dark themes";

      light = lib.mkOption {
        type = lib.types.str;
        default = "Apple System Colors Light";
        example = "Catppuccin Latte";
        description = "Theme used in macOS light mode (only when theme.auto = true).";
      };

      dark = lib.mkOption {
        type = lib.types.str;
        default = "Cursor Dark";
        example = "Catppuccin Macchiato";
        description = "Theme used in macOS dark mode (only when theme.auto = true).";
      };

      fixed = lib.mkOption {
        type = lib.types.str;
        default = "Catppuccin Macchiato";
        example = "Apple System Colors Dark";
        description = "Single theme name used when theme.auto = false.";
      };

      boldIsBright = lib.mkOption {
        type = lib.types.nullOr lib.types.bool;
        default = null;
        example = true;
        description = "Map bold text to the bright color palette. null = Ghostty default.";
      };

      customThemes = lib.mkOption {
        type = lib.types.attrsOf lib.types.str;
        default = { };
        example = lib.literalExpression ''
          { "rose-pine-moon" = builtins.readFile ./themes/rose-pine-moon; }
        '';
        description = ''
          Custom theme files keyed by theme name. Each entry is written to
          ~/.config/ghostty/themes/<name>, so the matching name can be used in
          theme.fixed or theme.light/dark.
        '';
      };
    };

    transparency = {
      opacity = lib.mkOption {
        type = lib.types.nullOr (lib.types.either lib.types.float lib.types.int);
        default = null;
        example = 0.85;
        description = "Background opacity 0.0–1.0. null = Ghostty default (opaque).";
      };

      blur = lib.mkOption {
        type = lib.types.nullOr (lib.types.either lib.types.int lib.types.str);
        default = null;
        example = "macos-glass-clear";
        description = "Background blur radius or named macOS glass mode. null = disabled.";
      };
    };

    font = {
      family = lib.mkOption {
        type = lib.types.str;
        default = "MonoLisa";
        example = "Maple Mono NF CN";
        description = "Primary font family (always quoted in the generated config).";
      };

      size = lib.mkOption {
        type = lib.types.int;
        default = 14;
        example = 15;
        description = "Font size in points.";
      };

      thicken = lib.mkOption {
        type = lib.types.bool;
        default = false;
        example = true;
        description = "Apply Ghostty's font-thicken (macOS only).";
      };

      adjustCellHeight = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        example = "15%";
        description = "Adjust cell height (e.g. \"15%\"). null = leave at default.";
      };

      style = {
        regular = lib.mkOption {
          type = lib.types.nullOr lib.types.str;
          default = null;
          example = "MonoLisa";
          description = "Override for the regular font-style face.";
        };
        italic = lib.mkOption {
          type = lib.types.nullOr lib.types.str;
          default = null;
          example = "MonoLisa Italic";
          description = "Override for the italic font-style face.";
        };
        bold = lib.mkOption {
          type = lib.types.nullOr lib.types.str;
          default = null;
          example = "MonoLisa Bold";
          description = "Override for the bold font-style face.";
        };
        boldItalic = lib.mkOption {
          type = lib.types.nullOr lib.types.str;
          default = null;
          example = "MonoLisa Bold Italic";
          description = "Override for the bold-italic font-style face.";
        };
      };
    };

    cursor = {
      style = lib.mkOption {
        type = lib.types.enum [ "block" "block_hollow" "underline" "bar" ];
        default = "block";
        example = "bar";
        description = "Cursor shape.";
      };

      blink = lib.mkOption {
        type = lib.types.bool;
        default = false;
        example = true;
        description = "Whether the cursor blinks.";
      };

      hideMouseWhileTyping = lib.mkOption {
        type = lib.types.bool;
        default = true;
        example = false;
        description = "Hide the mouse pointer while typing.";
      };
    };

    window = {
      titlebarStyle = lib.mkOption {
        type = lib.types.enum [ "native" "transparent" "tabs" "hidden" ];
        default = "transparent";
        example = "tabs";
        description = "macOS titlebar style.";
      };

      optionAsAlt = lib.mkOption {
        type = lib.types.bool;
        default = true;
        example = false;
        description = "Treat macOS Option as Alt.";
      };

      saveState = lib.mkOption {
        type = lib.types.enum [ "default" "never" "always" ];
        default = "always";
        example = "never";
        description = "Whether Ghostty restores window state across launches.";
      };

      quitAfterLastClosed = lib.mkOption {
        type = lib.types.bool;
        default = true;
        example = false;
        description = "Quit Ghostty after the last window closes.";
      };

      confirmClose = lib.mkOption {
        type = lib.types.bool;
        default = false;
        example = true;
        description = "Confirm before closing a surface that has running processes.";
      };

      colorspace = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        example = "display-p3";
        description = "Window colorspace. null = Ghostty default (sRGB).";
      };

      minimumContrast = lib.mkOption {
        type = lib.types.nullOr (lib.types.either lib.types.float lib.types.int);
        default = null;
        example = 1.1;
        description = "Minimum contrast ratio enforced against the theme. null = Ghostty default.";
      };

      title = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        example = "Ghostty";
        description = "Static window title. null lets running programs set it.";
      };

      padding = {
        x = lib.mkOption {
          type = lib.types.int;
          default = 4;
          example = 8;
          description = "Horizontal padding inside the window (cells).";
        };
        y = lib.mkOption {
          type = lib.types.int;
          default = 4;
          example = 6;
          description = "Vertical padding inside the window (cells).";
        };
        balance = lib.mkOption {
          type = lib.types.bool;
          default = true;
          example = false;
          description = "Distribute padding evenly across both sides.";
        };
        color = lib.mkOption {
          type = lib.types.str;
          default = "background";
          example = "#1e1e2e";
          description = "Color used for window padding (Ghostty window-padding-color).";
        };
      };
    };

    clipboard.enable = lib.mkEnableOption "clipboard read/write and copy-on-select";

    scrollback.lines = lib.mkOption {
      type = lib.types.int;
      default = 10000;
      example = 20000;
      description = "Scrollback buffer size in lines.";
    };

    shellIntegration = {
      shell = lib.mkOption {
        type = lib.types.enum [ "none" "detect" "bash" "fish" "zsh" ];
        default = "zsh";
        example = "detect";
        description = "Shell integration mode.";
      };

      features = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [ "cursor" "sudo" "title" ];
        example = [ "cursor" "sudo" "title" "ssh-env" ];
        description = "Enabled shell-integration features (joined with commas).";
      };
    };

    quickTerminal = {
      enable = lib.mkEnableOption "quick-terminal dropdown surface";

      position = lib.mkOption {
        type = lib.types.enum [ "top" "bottom" "left" "right" "center" ];
        default = "top";
        example = "bottom";
        description = "Edge the quick terminal slides in from.";
      };

      animationDuration = lib.mkOption {
        type = lib.types.float;
        default = 0.15;
        example = 0.2;
        description = "Quick terminal slide animation duration (seconds).";
      };
    };

    splits.enable = lib.mkEnableOption "cmd+d/cmd+shift+d split keybinds plus cmd+alt+arrow navigation and cmd+ctrl+arrow resize";

    tabs.enable = lib.mkEnableOption "cmd+shift+left/right tab navigation keybinds";
  };

  config = lib.mkIf cfg.enable {
    home.packages =
      lib.optionals (pkgs.stdenv.isDarwin && hasPackage "ghostty-bin") [
        pkgs.ghostty-bin
      ]
      ++ lib.optionals (!pkgs.stdenv.isDarwin && hasPackage "ghostty") [
        pkgs.ghostty.terminfo
      ];

    xdg.configFile = {
      "ghostty/config".text = configText;
    } // lib.mapAttrs'
      (name: contents: lib.nameValuePair "ghostty/themes/${name}" { text = contents; })
      cfg.theme.customThemes;
  };
}
