#!/usr/bin/env bash
# Discover Factory AI Droid CLI version + per-platform binary URLs from
# https://app.factory.ai/cli, then (re)generate pkgs/droid.nix and wire the
# package into pkgs/default.nix on first run.
#
# Best-effort parser: bails loudly when the install script's format doesn't
# match expectations. If this fires, inspect the script manually:
#     curl -fsSL https://app.factory.ai/cli | less
# and update the regexes below.
set -euo pipefail
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

INSTALLER_URL="https://app.factory.ai/cli"
TARGET="pkgs/droid.nix"
DEFAULT_NIX="pkgs/default.nix"

installer=$(curl -fsSL "$INSTALLER_URL")
[ -n "$installer" ] || { echo "could not fetch $INSTALLER_URL" >&2; exit 1; }

# Parse version: try several common shell-script idioms.
version=$(printf '%s\n' "$installer" \
  | grep -oE '(VERSION|CLI_VERSION|DROID_VERSION)="[^"]+"' \
  | head -1 | cut -d'"' -f2 || true)
if [ -z "${version:-}" ]; then
  version=$(printf '%s\n' "$installer" \
    | grep -oE '"version"[[:space:]]*:[[:space:]]*"[^"]+"' \
    | head -1 | sed -E 's/.*"([^"]+)"$/\1/' || true)
fi
[ -n "${version:-}" ] || {
  echo "could not parse Factory CLI version from installer" >&2
  echo "first 40 lines of installer:" >&2
  printf '%s\n' "$installer" | head -40 >&2
  exit 1
}

# Collect candidate download URLs from the install script.
mapfile -t urls < <(printf '%s\n' "$installer" \
  | grep -oE 'https://[A-Za-z0-9._-]+\.factory\.ai/[A-Za-z0-9._/?=&%-]+' \
  | sort -u)
[ "${#urls[@]}" -ge 1 ] || {
  echo "no Factory CDN URLs extracted from installer" >&2; exit 1; }

declare -A SOURCES
for url in "${urls[@]}"; do
  case "$url" in
    *darwin*arm64*|*aarch64*darwin*|*macos*arm64*|*darwin*aarch64*)
      plat="aarch64-darwin" ;;
    *darwin*x86_64*|*x86_64*darwin*|*macos*x86_64*|*darwin*amd64*)
      plat="x86_64-darwin" ;;
    *linux*x86_64*|*x86_64*linux*|*linux*amd64*)
      plat="x86_64-linux" ;;
    *linux*arm64*|*aarch64*linux*|*linux*aarch64*)
      plat="aarch64-linux" ;;
    *) continue ;;
  esac
  echo "prefetching $plat: $url"
  nar=$(nix-prefetch-url "$url" 2>/dev/null) || {
    echo "prefetch failed for $url (skipping)" >&2; continue; }
  sri=$(nix hash convert --to sri --hash-algo sha256 "$nar")
  SOURCES["$plat"]="${url}|${sri}"
done

[ "${#SOURCES[@]}" -ge 1 ] || {
  echo "no platform binaries identified" >&2; exit 1; }

{
  cat <<'EOF_HEAD'
# Factory AI Droid CLI — auto-generated by scripts/update-droid.sh.
# Do not hand-edit; bumps land via the auto-update workflow.
{ lib
, stdenv
, fetchurl
, autoPatchelfHook
, makeBinaryWrapper
,
}:

let
  sources = {
EOF_HEAD
  for plat in "${!SOURCES[@]}"; do
    IFS='|' read -r url sri <<<"${SOURCES[$plat]}"
    printf '    "%s" = { url = "%s"; hash = "%s"; };\n' "$plat" "$url" "$sri"
  done
  cat <<EOF_TAIL
  };

  source = sources.\${stdenv.hostPlatform.system}
    or (throw "factory-droid: unsupported platform \${stdenv.hostPlatform.system}");
in
stdenv.mkDerivation {
  pname = "droid";
  version = "${version}";

  src = fetchurl source;

  dontUnpack = true;
  dontStrip = true;

  nativeBuildInputs = [
    makeBinaryWrapper
  ] ++ lib.optionals stdenv.isLinux [
    autoPatchelfHook
  ];

  buildInputs = lib.optionals stdenv.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    runHook preInstall
    install -Dm755 "\$src" "\$out/bin/droid"
    runHook postInstall
  '';

  meta = {
    description = "Factory AI Droid CLI";
    homepage = "https://factory.ai/";
    license = lib.licenses.unfree;
    mainProgram = "droid";
    platforms = builtins.attrNames sources;
    sourceProvenance = with lib.sourceTypes; [ binaryNativeCode ];
  };
}
EOF_TAIL
} > "$TARGET"

# Register in pkgs/default.nix on first run.
if ! grep -q 'droid = final.callPackage ./droid.nix' "$DEFAULT_NIX"; then
  awk '
    /^    sourcegraph-amp = final\.callPackage / && !inserted {
      print "    droid = final.callPackage ./droid.nix { };"
      inserted = 1
    }
    { print }
  ' "$DEFAULT_NIX" > "$DEFAULT_NIX.tmp"
  mv "$DEFAULT_NIX.tmp" "$DEFAULT_NIX"
fi

nix build .#martin.droid --no-link
echo "droid bumped to $version"
